# Generated by Django 5.1.15 on 2026-10-01 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('wholesale_min_qty', models.PositiveIntegerField(default=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('safety_stock', models.PositiveIntegerField(default=0, help_text='Minimum reorder threshold.')),
                ('aisle', models.CharField(blank=True, default='', max_length=16)),
                ('rack', models.CharField(blank=True, default='', max_length=16)),
                ('shelf', models.CharField(blank=True, default='', max_length=16)),
                ('bin', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(limit_choices_to={'type': 'DISTRIBUTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.organization')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Empty = shared with every vendor.', related_name='shared_products', to='accounts.organization')),
            ],
            options={
                'ordering': ['sku_code'],
            },
        ),
        migrations.CreateModel(
            name='RestockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('trigger_stock', models.IntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to supplier'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_orders', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_qty', models.IntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('DAMAGED', 'Damaged'), ('ADJUSTED', 'Adjusted'), ('ORDER', 'Order deduction'), ('ORDER_CANCELLED', 'Order cancellation'), ('RESTOCK_RECEIVED', 'Restock received')], db_index=True, max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_code'], name='product_sku_btree_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'is_active'], name='product_org_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_qty__gte', 0)), name='product_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='restockorder',
            index=models.Index(fields=['status', 'created_at'], name='restock_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['product', 'created_at'], name='stocklog_product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['created_at'], name='stocklog_created_at_idx'),
        ),
    ]
