from celery import shared_task
from django.conf import settings
from django.core.mail import send_mail


@shared_task(name="inventory.low_stock_workflow")
def low_stock_workflow(product_id: int) -> dict:
    """Notify warehouse managers and queue a draft restock order (FR-INV-3)."""
    from apps.inventory.models import Product, RestockOrder
    from apps.accounts.models import User

    product = Product.objects.select_related("organization").filter(pk=product_id).first()
    if product is None or not product.is_low_stock:
        return {"skipped": True, "product_id": product_id}

    managers = list(
        User.objects.filter(
            organization_id=product.organization_id,
            role=User.Role.WAREHOUSE_MANAGER,
            is_active=True,
        ).values_list("email", flat=True)
    )

    subject = f"[Low Stock] {product.sku_code} below reorder threshold"
    body = (
        f"SKU: {product.sku_code} ({product.name})\n"
        f"Current stock: {product.stock_qty}\n"
        f"Reorder threshold: {product.safety_stock}\n"
        f"Location: {product.location or 'n/a'}\n\n"
        "A draft restocking order has been queued automatically."
    )
    if managers:
        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, managers, fail_silently=True)

    quantity = max(product.safety_stock * 2 - product.stock_qty, product.safety_stock, 1)
    restock, created = RestockOrder.objects.get_or_create(
        product=product,
        status=RestockOrder.Status.DRAFT,
        defaults={
            "quantity": quantity,
            "trigger_stock": product.stock_qty,
            "threshold": product.safety_stock,
            "notes": "Auto-generated by low-stock monitor.",
        },
    )
    return {
        "skipped": False,
        "product_id": product_id,
        "notified": managers,
        "restock_order_id": restock.id,
        "restock_created": created,
    }


@shared_task(name="inventory.daily_low_stock_scan")
def daily_low_stock_scan() -> dict:
    """Periodic sweep: every product currently below threshold gets the workflow."""
    from django.db.models import F

    from apps.inventory.models import Product

    ids = list(Product.objects.filter(stock_qty__lt=F("safety_stock")).values_list("pk", flat=True))
    for pk in ids:
        low_stock_workflow.delay(pk)
    return {"scanned": len(ids)}
