# Generated by Django 5.1.15 on 2026-10-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(db_index=True)),
                ('payment_terms', models.CharField(default='Net 30', max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAYMENT_SUBMITTED', 'Payment submitted'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], db_index=True, default='UNPAID', max_length=24)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('proof_of_payment', models.FileField(blank=True, default='', upload_to='proofs/')),
                ('pdf_file', models.FileField(blank=True, default='', upload_to='invoices/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='invoice_status_created_idx'), models.Index(fields=['created_at'], name='invoice_created_at_idx')],
            },
        ),
    ]
